# This is a basic workflow to help you get started with Actions
name: CD

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the main branch
  push:
    branches: [main]
  pull_request:
    branches: [main]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "deploy"
  deploy:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Add "id-token" with the intended permissions.
    permissions:
      contents: "read"
      id-token: "write"

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v4

      - id: "auth"
        name: "Authenticate to Google Cloud"
        uses: "google-github-actions/auth@v2"
        with:
          # Replace with your Workload Identity Provider Location
          workload_identity_provider: "projects/163476427985/locations/global/workloadIdentityPools/gh-pool/providers/gh-provider"
          # Replace with your GitHub Service Account
          service_account: "github-actions-service-account@img-share-api-project.iam.gserviceaccount.com"

      # - id: "deploy"
      #   uses: "google-github-actions/deploy-cloud-functions@v2"
      #   with:
      #     # Name of the Cloud Function, same as the entry point name
      #     name: "img-share-api-func"
      #     # Runtime to use for the function
      #     runtime: "go121"
      #     region: "us-central1"

      - name: 'Set up GCP SDK'
        uses: 'google-github-actions/setup-gcloud@v1'
        with:
          version: '>= 363.0.0'
      
      - name: 'Use gcloud CLI'
        run: 'gcloud info'
      - name: 'Use to deploy a cloud function gen 2'
        run: 'gcloud functions deploy img-share-api-func --gen2 --runtime=go122 --region=us-central1 --trigger-http --allow-unauthenticated --entry-point=imgShareAPIFunc --memory=256MB --timeout=60s'
    
    
    